name: Secret Detection

on:
  push:
    branches: [ master ]

jobs:
  detect_secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download new branch (optional)
        run: |
          git fetch origin master
          # This assumes your local branch is also named master
          git checkout master

      - name: Install TruffleHog
        uses: trufflesecurity/trufflehog@v3.78.0
        with:
          tools: trufflehog

      - name: Scan for Secrets
        run: ls -l /usr/bin

      - name: Fail Workflow if Secrets Found (Optional)
        run: exit 1
        if: ${{ contains(steps.detect_secrets.outputs, 'secrets_found') }}
